# Generated by Django 6.0.2 on 2026-02-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_department_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(default='1', help_text='Academic year: 1, 2, 3, 4, etc.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'department', 'year')},
        ),
    ]
