# Generated by Django 6.0.2 on 2026-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subject_add_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(default='1', help_text='Semester within year: 1 or 2', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'department', 'year', 'semester')},
        ),
    ]
