# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_add_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Number of hours attended out of total hours for this subject/date.',
                null=True,
            ),
        ),
    ]
