# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendance_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='hours',
            new_name='attended_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Total hours scheduled for this subject/date.',
                null=True,
            ),
        ),
    ]
