# Generated by Django 4.2.28 on 2026-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendance_attended_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of hours the student attended for this subject/date.', null=True),
        ),
    ]
